import {
  FISH,
  MUSHROOMS,
  SALMON,
  MEAT,
  type Ingredient,
  HYRULE_HERB,
  GORON_SPICE,
  CRAB,
  SALT,
  PEPPERS,
  STAMBULB,
  OIL,
  POULTRY,
  WHEAT,
  BUTTER,
  HONEY,
  RICE,
  CARROTS,
  PUMPKIN,
  CHEESE,
  EGGS,
  TOMATOES,
  SNAIL,
  MILK,
  NUTS,
  FRUIT,
  BANANA,
  SUGAR,
  APPLE,
  BERRY,
  COCONUT,
  MELON,
  DRAGONFRUIT,
} from './ingredients'
import { DESSERT, ENTREE, SIDE, SOUP, type MealCategory } from './meal_category'

export type Meal = {
  id: number
  name: string
  numbers: string
  ingredients: Ingredient[]
  category: MealCategory
}

export const MEALS: Meal[] = [
  {
    numbers: '1-8',
    name: 'Skewers (Meat, Mushroom, Fish, Seafood)',
    id: 1,
    ingredients: [MEAT, POULTRY, MUSHROOMS, FISH, SALMON],
    category: ENTREE,
  },
  {
    numbers: '12',
    name: 'Steamed Meat',
    id: 12,
    ingredients: [MEAT, POULTRY, HYRULE_HERB, STAMBULB],
    category: ENTREE,
  },
  {
    numbers: '13',
    name: 'Steamed Fish',
    id: 13,
    ingredients: [FISH, SALMON, HYRULE_HERB, STAMBULB],
    category: ENTREE,
  },
  {
    numbers: '21-23',
    name: 'Spiced Meat Skewer',
    id: 21,
    ingredients: [MEAT, POULTRY, GORON_SPICE],
    category: ENTREE,
  },
  {
    numbers: '24',
    name: 'Crab Stir Fry',
    id: 24,
    ingredients: [CRAB, GORON_SPICE],
    category: ENTREE,
  },
  {
    numbers: '25-27',
    name: 'Meat and Seafood Fry',
    id: 25,
    ingredients: [MEAT, POULTRY, FISH, SALMON, CRAB],
    category: ENTREE,
  },
  {
    numbers: '30-32',
    name: 'Salt-Grilled Meat',
    id: 30,
    ingredients: [MEAT, POULTRY, SALT],
    category: ENTREE,
  },
  {
    numbers: '33',
    name: 'Salt-Grilled Fish',
    id: 33,
    ingredients: [FISH, SALMON, SALT],
    category: ENTREE,
  },
  {
    numbers: '34',
    name: 'Salt-Grilled Crab',
    id: 34,
    ingredients: [CRAB, SALT],
    category: ENTREE,
  },
  {
    numbers: '37',
    name: 'Pepper Steak',
    id: 37,
    ingredients: [MEAT, POULTRY, PEPPERS, HYRULE_HERB, STAMBULB],
    category: ENTREE,
  },
  {
    numbers: '38',
    name: 'Pepper Seafood',
    id: 38,
    ingredients: [FISH, SALMON, CRAB, GORON_SPICE],
    category: ENTREE,
  },
  {
    numbers: '39',
    name: 'Fragrant Seafood Stew',
    id: 39,
    ingredients: [FISH, SALMON, STAMBULB, OIL],
    category: ENTREE,
  },
  {
    numbers: '40-42',
    name: 'Deep Fried Chicken',
    id: 40,
    ingredients: [POULTRY, OIL],
    category: ENTREE,
  },
  {
    numbers: '43-45',
    name: 'Fish Meunière',
    id: 43,
    ingredients: [FISH, SALMON, WHEAT, BUTTER],
    category: ENTREE,
  },
  {
    numbers: '63',
    name: 'Glazed Meat',
    id: 63,
    ingredients: [MEAT, POULTRY, HONEY],
    category: ENTREE,
  },
  {
    numbers: '64',
    name: 'Glazed Seafood',
    id: 64,
    ingredients: [MEAT, POULTRY, FISH, SALMON],
    category: ENTREE,
  },
  {
    numbers: '65',
    name: 'Curry Rice',
    id: 65,
    ingredients: [RICE, GORON_SPICE],
    category: ENTREE,
  },
  {
    numbers: '66-73',
    name: 'Curries (Vegetable, Meat, Poultry, Seafood, Cheesy)',
    id: 66,
    ingredients: [RICE, GORON_SPICE, MEAT, POULTRY, CARROTS, PUMPKIN, FISH, SALMON, CHEESE],
    category: ENTREE,
  },
  {
    numbers: '79',
    name: 'Meat-Stuffed Pumpkin',
    id: 79,
    ingredients: [MEAT, POULTRY, PUMPKIN],
    category: ENTREE,
  },
  {
    numbers: '80-84',
    name: 'Risottos (Vegetable, Mushroom, Salmon, Crab, Cheese)',
    id: 80,
    ingredients: [CARROTS, PUMPKIN, MUSHROOMS, RICE, BUTTER, SALT, CRAB, CHEESE],
    category: ENTREE,
  },
  {
    numbers: '85-87',
    name: 'Poultry Pilaf',
    id: 85,
    ingredients: [POULTRY, EGGS, RICE, BUTTER],
    category: ENTREE,
  },
  {
    numbers: '88',
    name: 'Seafood Paella',
    id: 88,
    ingredients: [FISH, SALMON, CRAB, RICE, BUTTER, SALT],
    category: ENTREE,
  },
  {
    numbers: '89',
    name: 'Curry Pilaf',
    id: 89,
    ingredients: [RICE, EGGS, BUTTER, GORON_SPICE],
    category: ENTREE,
  },
  {
    numbers: '90',
    name: 'Fried Egg and Rice',
    id: 90,
    ingredients: [EGGS, RICE],
    category: ENTREE,
  },
  {
    numbers: '91',
    name: 'Crunchy Fried Rice',
    id: 91,
    ingredients: [MEAT, POULTRY, EGGS, RICE, OIL],
    category: ENTREE,
  },
  {
    numbers: '92',
    name: 'Seafood Fried Rice',
    id: 92,
    ingredients: [FISH, SALMON, RICE, SALT],
    category: ENTREE,
  },
  {
    numbers: '93',
    name: 'Crab Omelet with Rice',
    id: 93,
    ingredients: [CRAB, EGGS, RICE, SALT],
    category: ENTREE,
  },
  {
    numbers: '94-96',
    name: 'Meat and Rice Bowl',
    id: 94,
    ingredients: [MEAT, POULTRY, RICE, SALT],
    category: ENTREE,
  },
  {
    numbers: '97-99',
    name: 'Cheesy Meat Bowl',
    id: 97,
    ingredients: [MEAT, POULTRY, CHEESE, RICE, SALT],
    category: ENTREE,
  },
  {
    numbers: '107',
    name: 'Hylian Tomato Pizza',
    id: 107,
    ingredients: [WHEAT, TOMATOES, CHEESE],
    category: ENTREE,
  },
  {
    numbers: '108',
    name: 'Meat Pie',
    id: 108,
    ingredients: [MEAT, POULTRY, WHEAT, BUTTER, SALT],
    category: ENTREE,
  },
  {
    numbers: '109',
    name: 'Fish Pie',
    id: 109,
    ingredients: [FISH, SALMON, WHEAT, BUTTER, SALT],
    category: ENTREE,
  },
  {
    numbers: '111',
    name: 'Cheesy Baked Fish',
    id: 111,
    ingredients: [FISH, SALMON, CRAB, SNAIL, CHEESE],
    category: ENTREE,
  },
  {
    numbers: '112-115',
    name: 'Omelets (Vegetable, Mushroom, Cheesy)',
    id: 112,
    ingredients: [EGGS, BUTTER, SALT, MUSHROOMS, CHEESE, HYRULE_HERB, STAMBULB],
    category: ENTREE,
  },
  {
    numbers: '51',
    name: 'Tomato Mushroom Stew',
    id: 51,
    ingredients: [TOMATOES, MUSHROOMS],
    category: SOUP,
  },
  {
    numbers: '52',
    name: 'Tomato Seafood Soup',
    id: 52,
    ingredients: [TOMATOES, FISH, SALMON, CRAB, SNAIL],
    category: SOUP,
  },
  {
    numbers: '53',
    name: 'Cream of Vegetable Soup',
    id: 53,
    ingredients: [MILK, SALT, HYRULE_HERB, STAMBULB],
    category: SOUP,
  },
  {
    numbers: '54',
    name: 'Veggie Cream Soup',
    id: 54,
    ingredients: [CARROTS, PUMPKIN, MILK, SALT],
    category: SOUP,
  },
  {
    numbers: '55',
    name: 'Cream of Mushroom Soup',
    id: 55,
    ingredients: [MUSHROOMS, HYRULE_HERB, STAMBULB, MILK, SALT],
    category: SOUP,
  },
  {
    numbers: '56',
    name: 'Creamy Meat Soup',
    id: 56,
    ingredients: [MEAT, POULTRY, HYRULE_HERB, STAMBULB, MILK, SALT],
    category: SOUP,
  },
  {
    numbers: '57',
    name: 'Creamy Seafood Soup',
    id: 57,
    ingredients: [FISH, SALMON, CRAB, SNAIL, HYRULE_HERB, STAMBULB, MILK, SALT],
    category: SOUP,
  },
  {
    numbers: '58',
    name: 'Creamy Snail Chowder',
    id: 58,
    ingredients: [SNAIL, WHEAT, BUTTER, MILK],
    category: SOUP,
  },
  {
    numbers: '74',
    name: 'Carrot Stew',
    id: 74,
    ingredients: [CARROTS, WHEAT, BUTTER, MILK],
    category: SOUP,
  },
  {
    numbers: '75',
    name: 'Pumpkin Stew',
    id: 75,
    ingredients: [PUMPKIN, WHEAT, BUTTER, MILK],
    category: SOUP,
  },
  {
    numbers: '76-78',
    name: 'Meat Stew',
    id: 76,
    ingredients: [MEAT, POULTRY, WHEAT, BUTTER, MILK],
    category: SOUP,
  },
  {
    numbers: '11',
    name: 'Steamed Mushrooms',
    id: 11,
    ingredients: [MUSHROOMS, HYRULE_HERB, STAMBULB],
    category: SIDE,
  },
  {
    numbers: '14',
    name: 'Sautéed Peppers',
    id: 14,
    ingredients: [PEPPERS],
    category: SIDE,
  },
  {
    numbers: '149',
    name: 'Charred Pepper',
    id: 149,
    ingredients: [PEPPERS],
    category: SIDE,
  },
  {
    numbers: '15',
    name: 'Sautéed Nuts',
    id: 15,
    ingredients: [NUTS],
    category: SIDE,
  },
  {
    numbers: '16',
    name: 'Fried Wild Greens',
    id: 16,
    ingredients: [HYRULE_HERB, STAMBULB],
    category: SIDE,
  },
  {
    numbers: '19',
    name: 'Buttered Stambulb',
    id: 19,
    ingredients: [STAMBULB, BUTTER],
    category: SIDE,
  },
  {
    numbers: '28',
    name: 'Salt-Grilled Greens',
    id: 28,
    ingredients: [HYRULE_HERB, STAMBULB, SALT],
    category: SIDE,
  },
  {
    numbers: '29',
    name: 'Salt-Grilled Mushrooms',
    id: 29,
    ingredients: [MUSHROOMS, SALT],
    category: SIDE,
  },
  {
    numbers: '35',
    name: 'Herb Sauté',
    id: 35,
    ingredients: [HYRULE_HERB, STAMBULB, GORON_SPICE],
    category: SIDE,
  },
  {
    numbers: '36',
    name: 'Fragrant Mushroom Sauté',
    id: 36,
    ingredients: [MUSHROOMS, GORON_SPICE],
    category: SIDE,
  },
  {
    numbers: '46',
    name: 'Fruit and Mushroom Mix',
    id: 46,
    ingredients: [FRUIT, MELON, COCONUT, DRAGONFRUIT, APPLE, BANANA, MUSHROOMS],
    category: SIDE,
  },
  {
    numbers: '49',
    name: 'Simmered Tomato',
    id: 49,
    ingredients: [TOMATOES],
    category: SIDE,
  },
  {
    numbers: '50',
    name: 'Fruity Tomato Stew',
    id: 50,
    ingredients: [TOMATOES, MILK, SALT],
    category: SOUP,
  },
  {
    numbers: '60',
    name: 'Glazed Veggies',
    id: 60,
    ingredients: [HYRULE_HERB, STAMBULB, HONEY],
    category: SIDE,
  },
  {
    numbers: '61',
    name: 'Glazed Mushrooms',
    id: 61,
    ingredients: [MUSHROOMS, HONEY],
    category: SIDE,
  },
  {
    numbers: '100-104',
    name: 'Rice Balls (Veggie, Mushroom, Meat, Seafood)',
    id: 100,
    ingredients: [HYRULE_HERB, STAMBULB, MUSHROOMS, MEAT, POULTRY, FISH, SALMON, CRAB, SNAIL, RICE],
    category: SIDE,
  },
  {
    numbers: '104',
    name: 'Veggie Porridge',
    id: 104,
    ingredients: [HYRULE_HERB, MILK, RICE],
    category: SIDE,
  },
  {
    numbers: '105',
    name: 'Wheat Bread',
    id: 105,
    ingredients: [WHEAT, SALT],
    category: SIDE,
  },
  {
    numbers: '106',
    name: 'Melty Cheese Bread',
    id: 106,
    ingredients: [WHEAT, CHEESE],
    category: SIDE,
  },
  {
    numbers: '110',
    name: 'Cheesy Tomato',
    id: 110,
    ingredients: [WHEAT, TOMATOES, CHEESE],
    category: SIDE,
  },
  {
    numbers: '120',
    name: 'Fried Bananas',
    id: 120,
    ingredients: [BANANA, WHEAT, SUGAR],
    category: SIDE,
  },
  {
    numbers: '195',
    name: 'Roasted Tree Nut',
    id: 195,
    ingredients: [NUTS],
    category: SIDE,
  },
  {
    numbers: '9',
    name: 'Steamed Fruit',
    id: 9,
    ingredients: [HYRULE_HERB, STAMBULB, FRUIT, MELON, COCONUT, DRAGONFRUIT, APPLE, BANANA],
    category: DESSERT,
  },
  {
    numbers: '47',
    name: 'Simmered Fruit',
    id: 47,
    ingredients: [FRUIT, MELON, COCONUT, DRAGONFRUIT, APPLE, BANANA],
    category: DESSERT,
  },
  {
    numbers: '147',
    name: 'Baked Apple',
    id: 147,
    ingredients: [APPLE],
    category: DESSERT,
  },
  {
    numbers: '116',
    name: 'Hot Buttered Apple',
    id: 116,
    ingredients: [APPLE, BUTTER],
    category: DESSERT,
  },
  {
    numbers: '117',
    name: 'Honeyed Fruits',
    id: 117,
    ingredients: [HONEY, FRUIT, MELON, COCONUT, DRAGONFRUIT, BANANA],
    category: DESSERT,
  },
  {
    numbers: '118',
    name: 'Honeyed Apple',
    id: 118,
    ingredients: [APPLE, HONEY],
    category: DESSERT,
  },
  {
    numbers: '119',
    name: 'Honey Candy',
    id: 119,
    ingredients: [HONEY],
    category: DESSERT,
  },
  {
    numbers: '121',
    name: 'Egg Pudding',
    id: 121,
    ingredients: [EGGS, MILK, SUGAR],
    category: DESSERT,
  },
  {
    numbers: '122-124',
    name: 'Crêpes: (Plain, Wildberry, Honey)',
    id: 122,
    ingredients: [WHEAT, EGGS, MILK, BUTTER, SUGAR, BERRY, HONEY],
    category: DESSERT,
  },
  {
    numbers: '125',
    name: 'Nut Cake',
    id: 125,
    ingredients: [NUTS, WHEAT, SUGAR, BUTTER],
    category: DESSERT,
  },
  {
    numbers: '126',
    name: 'Fruit Cake',
    id: 126,
    ingredients: [FRUIT, MELON, COCONUT, DRAGONFRUIT, APPLE, BANANA, WHEAT, SUGAR],
    category: DESSERT,
  },
  {
    numbers: '127',
    name: 'Carrot Cake',
    id: 127,
    ingredients: [CARROTS, WHEAT, BUTTER, SUGAR],
    category: DESSERT,
  },
  {
    numbers: '128',
    name: 'Pumpkin Pie',
    id: 128,
    ingredients: [PUMPKIN, WHEAT, BUTTER, SUGAR],
    category: DESSERT,
  },
  {
    numbers: '129',
    name: 'Cheesecake',
    id: 129,
    ingredients: [CHEESE, WHEAT, SUGAR],
    category: DESSERT,
  },
  {
    numbers: '130',
    name: 'Fruit Pie',
    id: 130,
    ingredients: [FRUIT, MELON, COCONUT, DRAGONFRUIT, BANANA, WHEAT, BUTTER, SUGAR],
    category: DESSERT,
  },
  {
    numbers: '131',
    name: 'Apple Pie',
    id: 131,
    ingredients: [APPLE, SUGAR, WHEAT, BUTTER],
    category: DESSERT,
  },
  {
    numbers: '132',
    name: 'Egg Tart',
    id: 132,
    ingredients: [EGGS, WHEAT, BUTTER, SUGAR],
    category: DESSERT,
  },
  {
    numbers: '133',
    name: 'Noble Pursuit',
    id: 133,
    ingredients: [COCONUT, MELON, DRAGONFRUIT, SALT],
    category: DESSERT,
  },
]
